language: go
go: 
  - 1.6
  - tip

install:
  - go get github.com/constabulary/gb/...
  - gb vendor restore

script:
  - GOOS=linux GOARCH=amd64 gb build
  - GOOS=windows GOARCH=amd64 gb build
  - ls -la
  - ls -la bin

